source 'https://github.com/CocoaPods/Specs.git'
plugin 'cocoapods-binary'
install! 'cocoapods', :integrate_targets => false

use_frameworks!
platform :ios, '11.0'

target "TiFirebasedynamiclinks" do
    pod "FirebaseDynamicLinks", '7.3.1', :binary => true
end
